/* confdefs.h */
#define PACKAGE_NAME "mos_release"
#define PACKAGE_TARNAME "mos_release"
#define PACKAGE_VERSION "version-0.3"
#define PACKAGE_STRING "mos_release version-0.3"
#define PACKAGE_BUGREPORT "ajamshed@ndsl.kaist.edu"
#define PACKAGE_URL ""
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRINGS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
#define HAVE_FCNTL_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_LIMITS_H 1
#define HAVE_STDDEF_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_STRINGS_H 1
#define HAVE_SYS_PARAM_H 1
#define HAVE_SYS_TIME_H 1
#define HAVE_UNISTD_H 1
#define LSTAT_FOLLOWS_SLASHED_SYMLINK 1
#define HAVE_STDLIB_H 1
#define HAVE_MALLOC 1
#define HAVE_FTRUNCATE 1
#define HAVE_GETTIMEOFDAY 1
#define HAVE_MEMSET 1
#define HAVE_STRCASECMP 1
#define HAVE_STRCHR 1
#define HAVE_STRPBRK 1
#define HAVE_STRRCHR 1
#define HAVE_STRSTR 1
